// pwa/constants.tsx

import { Screen } from "./types";
import {
	Globe,
	Timer,
	Activity,
	TrendingDown,
	Rss,
	Move,
	Sigma,
	CandlestickChart,
	Combine,
	GitMerge,
	Shield,
	TrendingUp,
	Anchor,
	AlertTriangle,
	Gauge,
	Layers,
	BarChartHorizontal,
	Waves,
	Wind,
	Signal,
	AreaChart,
	Target,
	GripVertical,
	X,
	Sun,
	Moon,
	DollarSign,
	Percent,
	Menu,
	ArrowLeft,
	Bell,
	Home,
	Search,
	Send,
	XCircle,
	User,
	Key,
	Settings,
	LogOut,
	Play,
	Square,
	History,
	Edit,
	Trash2,
	FileText,
	Link2,
	Star,
	Loader,
	Plus,
	ChevronDown,
	ChevronUp,
	Check,
	Copy,
	Wallet,
} from "lucide-react";

export const ICONS = {
	Sun: Sun,
	Loader: Loader,
	Moon: Moon,
	Dollar: DollarSign,
	Percent: Percent,
	TrendingDown: TrendingDown,
	Star: Star,
	Menu: Menu,
	Back: ArrowLeft,
	Notifications: Bell,
	Home: Home,
	Strategies: Target,
	Research: Search,
	Send: Send,
	Close: XCircle,
	Profile: User,
	Key: Key,
	Settings: Settings,
	Logout: LogOut,
	Play: Play,
	Stop: Square,
	History: History,
	Edit: Edit,
	Trash: Trash2,
	Trash2: Trash2,
	Plus: Plus,
	ChevronDown: ChevronDown,
	ChevronUp: ChevronUp,
	FileText: FileText,
	Link2: Link2,
	Check: Check,
	Copy: Copy,
	Wallet: Wallet,
	Language: Globe,

	// Block-specific icons from desktop app
	trading_session: Timer,
	volatility_filter: Activity,
	trend_filter: TrendingDown,
	senior_tf_confluence: Rss,
	btc_state_filter: Globe,
	correlation: GitMerge,
	natr_filter: Activity,
	rel_vol_filter: Gauge,
	volatility_squeeze: Activity,

	tape_analysis: Wind,
	order_book_zone: Layers,
	l2_microstructure: Shield,
	l2_microstructure_check: Shield,
	local_level: AreaChart,
	significant_level: Anchor,
	round_level: Target,
	trend_direction: TrendingUp,
	classic_pattern: CandlestickChart,
	volume_confirmation: Signal,
	price_consolidation: Waves,
	open_interest: Rss,
	tradingview_signal: Signal,
	price_action_analyzer: CandlestickChart,
	level_touch_analyzer: Target,

	market_activity: Activity,
	pattern: CandlestickChart,
	return_to_level: Move,
	order_book_analysis: Layers,
	tape_acceleration: Wind,
	aggregated_density_check: Gauge,
	tape_condition: Wind,
	order_book_zone_condition: Layers,
	level_proximity_condition: Target,
	price_condition: DollarSign,

	ma_cross_condition: Move,
	rsi_condition: Settings,
	value_comparison: Sigma,
	macd_condition: BarChartHorizontal,
	bollinger_bands_condition: Waves,
	stochastic_condition: Wind,
	price_vs_level: Target,

	AND: Combine,
	OR: GitMerge,

	trailing_stop: TrendingUp,
	move_to_breakeven: Anchor,
	conditional_exit: AlertTriangle,
	scale_in: TrendingUp,
	conditional_management: Settings,
	modify_stop_loss: Move,
	modify_take_profit: Target,
	close_position: AlertTriangle,
	dca_management: Sigma,
	grid_management: Layers,

	open_position: Play,
	GripVertical: GripVertical,
	X: X,
	Sigma: Sigma,
};

// Specify that the return type is an object,
// where the keys are values from Screen, and the values are strings.
export const getScreenTitles = (
	t: (key: string) => string,
): Record<Screen, string> => ({
	[Screen.Auth]: "Authentication",
	[Screen.Dashboard]: t("header.dashboard"),
	[Screen.Strategies]: t("header.strategies"),
	[Screen.Research]: t("header.research"),
	[Screen.Notifications]: t("header.notifications"),
	[Screen.AIChat]: t("header.aiChat"),
	[Screen.Editor]: t("header.editor"),
	[Screen.BacktestResult]: t("header.backtestResult"),
	[Screen.Profile]: t("header.profile"),
	[Screen.Settings]: t("header.settings"),
	[Screen.ForgotPassword]: t("auth.forgotPasswordTitle"),
	[Screen.ResetPassword]: t("auth.resetPasswordTitle"),
});

export const getNavItems = (t: (key: string) => string) => [
	{ id: Screen.Dashboard, label: t("nav.dashboard"), icon: ICONS.Home },
	{ id: Screen.Strategies, label: t("nav.strategies"), icon: ICONS.Strategies },
	{ id: Screen.Research, label: t("nav.research"), icon: ICONS.Research },
	{
		id: Screen.Notifications,
		label: t("nav.notifications"),
		icon: ICONS.Notifications,
	},
];
