# tests/test_ui_schema_roundtrip_integrity.py
"""
UI Schema Round-Trip Contract & End-to-End Execution Integrity Test Suite.

Validates that real JSON exports generated by the Visual Strategy Editor (React/TypeScript)
pass Pydantic validation (StrategyV2ConfigData), serialize/deserialize without data loss,
initialize the VisualBuilderStrategy engine cleanly, and execute all condition trees,
composite blocks, dynamic parameters, multi-timeframe containers, and position management
lifecycles across Binance, Bybit, OKX, and Weex data feeds.
"""

import json
import os
import time
from typing import Dict, Any, Set, Optional
import pytest

# Ensure mock database env vars are set before importing api
os.environ.setdefault("POSTGRES_USER", "testuser")
os.environ.setdefault("POSTGRES_PASSWORD", "testpassword")
os.environ.setdefault("POSTGRES_DB", "testdb")
os.environ.setdefault("POSTGRES_HOST", "localhost")
os.environ.setdefault("POSTGRES_PORT", "5432")

from api import schemas
from bot_module.strategy import (
    VisualBuilderStrategy,
    StrategySignal,
    BasePosition,
    SignalDirection,
)
from tests.test_exchange_blocks_matrix import create_exchange_context


import copy
import glob

# ============================================================================================
# EMBEDDED GOLDEN MASTER CONFIG (Matches React UI Strategy Editor Export Verbatim)
# ============================================================================================
GOLDEN_UI_MASTER_CONFIG: Dict[str, Any] = {
    "strategy_name": "VisualBuilderStrategy",
    "signal_source": "internal",
    "symbol": "BTCUSDT",
    "marketType": "FUTURES",
    "min_foundation_weight_threshold": 0,
    "foundation_weights": None,
    "filters": {
        "id": "filters_root",
        "type": "AND",
        "children": [
            {
                "id": "655ecc07-adab-4493-92cc-02351c6e72ca",
                "type": "trading_session",
                "params": {"session": "london"},
            },
            {
                "id": "71b596a2-af40-40ed-9040-75e5c17f2963",
                "type": "volatility_filter",
                "params": {"indicator": "ATR", "operator": "gt", "value": 1.5},
            },
            {
                "id": "626acd3e-6320-403f-9a91-1ce775706ffe",
                "type": "trend_filter",
                "params": {"indicator": "ADX", "threshold": 25},
            },
            {
                "id": "b0cc9c99-b1f6-4396-bc0f-07e139248047",
                "type": "senior_tf_confluence",
                "params": {"timeframe": "1h"},
                "children": [],
            },
            {
                "id": "28d8b7e1-12d7-4c65-9445-c479a85dab0e",
                "type": "btc_state_filter",
                "params": {"required_state": "Consolidation"},
            },
            {
                "id": "2a5fa3a1-ec1a-42c4-9b84-28b35ac00cd6",
                "type": "correlation",
                "params": {"lookback": 50, "operator": "lt", "value": 0.7},
            },
            {
                "id": "56dd0000-3ac7-4693-aa46-2a04f2b19ca3",
                "type": "correlation",
                "params": {"lookback": 50, "operator": "lt", "value": 0.7},
            },
            {
                "id": "791cc070-883a-42a8-beba-eefbf2204a8f",
                "type": "natr_filter",
                "params": {"natr_threshold": 1},
            },
            {
                "id": "3049a82f-8f23-4606-878e-f80591b4279a",
                "type": "rel_vol_filter",
                "params": {"mode": "relative", "rel_vol_threshold": 1.5},
            },
            {
                "id": "f2809c47-5aaa-425c-9afc-826a8bed8d9d",
                "type": "volatility_squeeze",
                "params": {"lookback_candles": 20, "squeeze_ratio": 0.6},
            },
        ],
    },
    "entryTrigger": {"type": "on_candle_close", "timeframe": "5m"},
    "entryConditions": {
        "id": "entry_root",
        "type": "AND",
        "children": [
            {
                "id": "b8641dd2-a508-4516-bc71-02dbe36935e0",
                "type": "market_activity",
                "params": {
                    "mode": "percentile",
                    "natr_threshold": 1,
                    "rel_vol_threshold": 1.5,
                },
            },
            {
                "id": "ce6a2f58-e48e-4664-a2e2-ae8eca9326e2",
                "type": "AND",
                "isComposite": True,
                "compositeType": "tape_condition",
                "children": [
                    {
                        "id": "f761fd86-0ebc-43d8-9ba8-99401b87e5a5",
                        "type": "tape_analysis",
                        "params": {"time_window_sec": 5},
                    },
                    {
                        "id": "48652957-5944-4ec7-a32f-6621c785340d",
                        "type": "value_comparison",
                        "params": {
                            "operator": "gt",
                            "rightOperand": 0,
                            "leftOperand": {
                                "source": "block_result",
                                "block_id": "f761fd86-0ebc-43d8-9ba8-99401b87e5a5",
                                "key": "total_volume_usd",
                            },
                        },
                    },
                ],
            },
            {
                "id": "18e9cf7c-0f71-44dc-baa7-d41bd85c4dde",
                "type": "AND",
                "isComposite": True,
                "compositeType": "order_book_zone_condition",
                "children": [
                    {
                        "id": "0b87d1fa-8533-45fd-aa0b-b8f195ff0d7d",
                        "type": "order_book_zone",
                        "params": {
                            "side": "bids",
                            "range_type": "Percentage",
                            "range_value": 1,
                        },
                    },
                    {
                        "id": "c2cab86a-6358-4eac-b58e-f7e3a7f6826b",
                        "type": "value_comparison",
                        "params": {
                            "operator": "gt",
                            "rightOperand": 1000000,
                            "leftOperand": {
                                "source": "block_result",
                                "block_id": "0b87d1fa-8533-45fd-aa0b-b8f195ff0d7d",
                                "key": "total_volume_usd",
                            },
                        },
                    },
                    {
                        "id": "a7dbbf09-1a57-470c-bbf4-43d4694c06a3",
                        "type": "significant_level",
                        "params": {
                            "level_type": "daily_high",
                            "proximity_type": "percentage",
                            "proximity_value": 0.2,
                        },
                    },
                ],
            },
            {
                "id": "9257b677-020a-431b-b2e0-628732ba39a9",
                "type": "AND",
                "isComposite": True,
                "compositeType": "level_proximity_condition",
                "children": [
                    {
                        "id": "db527850-0c68-425d-82f4-8414fea620aa",
                        "type": "local_level",
                        "params": {
                            "timeframe": "1h",
                            "lookback_period": 24,
                            "level_type": "high",
                            "proximity_type": "percentage",
                            "proximity_value": 0.2,
                            "is_data_provider": False,
                        },
                    }
                ],
            },
            {
                "id": "dd310a85-8040-40d5-8d5f-af64485fba0a",
                "type": "l2_microstructure",
                "params": {
                    "check_type": "large_order",
                    "single_order_size_usd": 250000,
                    "side": "bids",
                    "levels_to_scan": 200,
                },
            },
            {
                "id": "58ad4ccd-51a5-466e-a0b6-ab8f27963db0",
                "type": "significant_level",
                "params": {
                    "level_type": "daily_high",
                    "proximity_type": "percentage",
                    "proximity_value": 0.2,
                },
            },
            {
                "id": "fde30d09-0263-4add-97a6-fd71a7fc8eea",
                "type": "round_level",
                "params": {
                    "proximity_type": "percentage",
                    "proximity_value": 0.2,
                },
            },
            {
                "id": "96c58f30-a284-4f19-bdba-3dfb41a00672",
                "type": "trend_direction",
                "params": {
                    "timeframe": "15m",
                    "required_trend": "LONG",
                    "fast_period": 10,
                    "slow_period": 50,
                    "rsi_period": 14,
                    "rsi_lower_bound": 40,
                    "rsi_upper_bound": 60,
                },
            },
            {
                "id": "165d2df3-c4b0-4e91-913f-d58f9620c0ef",
                "type": "classic_pattern",
                "params": {"pattern_name": "bullish_engulfing"},
            },
            {
                "id": "ca5eb86d-2496-4e8c-9745-7edd65908adb",
                "type": "volume_confirmation",
                "params": {"multiplier": 1.5},
            },
            {
                "id": "e7a261af-8d65-4539-af34-8d085df903cc",
                "type": "price_consolidation",
                "params": {
                    "lookback_period": 10,
                    "max_range_atr": 0.8,
                    "timeframe": "auto",
                },
            },
            {
                "id": "f4eee601-4070-432e-bcea-6f27f5c9a7f6",
                "type": "open_interest",
                "params": {
                    "analyze": "change_pct",
                    "lookback": 5,
                    "operator": "gt",
                    "value": 1,
                },
            },
            {
                "id": "524bcc9a-65c1-42b6-8cb6-ac271299188c",
                "type": "tradingview_signal",
                "params": {"signal_id": "buy_signal_1", "ttl_seconds": 60},
            },
            {
                "id": "b3ce5179-b8f3-4a7f-8c1b-866f4a0c5e6e",
                "type": "price_action_analyzer",
                "params": {
                    "structure_type": "higher_lows",
                    "lookback_candles": 30,
                    "min_points": 2,
                    "order": 3,
                },
            },
            {
                "id": "50fc236e-8d83-4928-a723-8457dd04d7a5",
                "type": "level_touch_analyzer",
                "params": {
                    "level_source": None,
                    "lookback_candles": 50,
                    "touch_tolerance_pct": 0.1,
                    "invalidate_on_pierce": True,
                    "min_touches": 3,
                },
            },
            {
                "id": "6b102d26-24ee-4449-b19d-e08e19503aa3",
                "type": "return_to_level",
                "params": {
                    "level_block_id": None,
                    "retest_type": "touch",
                    "approach_direction": "any",
                    "confirmation_time_sec": 5,
                    "cooldown_sec": 60,
                    "proximity_type": "atr_multiplier",
                    "proximity_value": 0.1,
                    "departure_type": "atr_multiplier",
                    "departure_value": 1.5,
                },
            },
            {
                "id": "12e5a123-5313-4285-b4ca-decd753fe548",
                "type": "AND",
                "params": {},
                "children": [],
            },
            {
                "id": "46e21c0a-b67b-4b1c-a211-1b2f89b80c21",
                "type": "OR",
                "params": {},
                "children": [],
            },
        ],
    },
    "initialization": {
        "id": "init_action_1",
        "type": "open_position",
        "params": {
            "direction": "LONG",
            "risk_type": "percent_balance",
            "risk_value": 1,
            "sl_type": "atr_multiplier",
            "sl_value": 1.5,
            "tp_type": "rr_multiplier",
            "tp_value": 2,
            "partial_exits": [],
        },
    },
    "positionManagement": [
        {
            "id": "6d227ec9-ba9a-432b-9155-a5dc28222b9a",
            "type": "trailing_stop",
            "params": {"type": "Percentage", "value": 2, "mode": "local"},
        },
        {
            "id": "227c5117-99eb-4db3-bc11-8dbfd7c681c7",
            "type": "move_to_breakeven",
            "params": {
                "target_type": "rr_multiplier",
                "target_value": 1,
                "offset_pips": 2,
            },
        },
        {
            "id": "f5b3eadd-3a63-4f08-a474-8c1c965756d8",
            "type": "conditional_exit",
            "params": {},
        },
        {
            "id": "0b05aae8-6238-4b74-bee7-ac333db3bff1",
            "type": "scale_in",
            "params": {"add_size_pct_of_initial_risk": 100, "max_entries": 3},
        },
        {
            "id": "1bca2f63-7a36-4fa9-8ad5-07c012eb2727",
            "type": "dca_management",
            "params": {
                "max_safety_orders": 5,
                "volume_multiplier": 1.5,
                "step_type": "percentage",
                "step_value": 1,
            },
        },
        {
            "id": "1ee41e22-6330-45eb-8262-fe25229d0eb6",
            "type": "grid_management",
            "params": {
                "grid_levels": 10,
                "range_type": "percentage",
                "upper_bound": 5,
                "lower_bound": 5,
            },
        },
        {
            "id": "e555ea9d-3bfa-41ab-9010-4901f70972ca",
            "type": "conditional_management",
            "if_conditions": {
                "id": "4c9cddbf-ef15-4d51-bb02-c7225641f765",
                "type": "AND",
                "children": [],
            },
            "then_actions": [],
        },
    ],
    "oracle_regime": None,
    "oracle_confidence": 0,
    "use_ml_confirmation": False,
    "breakeven_on_regime_change": False,
}


def load_raw_ui_config(file_path: Optional[str] = None) -> Dict[str, Any]:
    """
    Loads UI strategy config.
    1. Checks explicit file_path if provided.
    2. Checks UI_STRATEGY_TEST_PATH env var.
    3. Searches workspace root for 'New_Strategy_config*.json'.
    4. Falls back to embedded GOLDEN_UI_MASTER_CONFIG (100% standalone, zero external file dependency).
    """
    # 1. Explicit path
    if file_path and os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)

    # 2. Env variable
    env_path = os.getenv("UI_STRATEGY_TEST_PATH")
    if env_path and os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            return json.load(f)

    # 3. Search in workspace root
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    candidates = glob.glob(os.path.join(root_dir, "New_Strategy_config*.json"))
    if candidates and os.path.exists(candidates[0]):
        try:
            with open(candidates[0], "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass

    # 4. Fallback to embedded Golden Master
    return copy.deepcopy(GOLDEN_UI_MASTER_CONFIG)


def _collect_node_ids(node: Dict[str, Any], collected: Set[str]) -> None:
    """Recursively collects all UUIDs/node IDs from a condition tree."""
    if not isinstance(node, dict):
        return
    node_id = node.get("id")
    if node_id:
        collected.add(node_id)
    children = node.get("children")
    if isinstance(children, list):
        for child in children:
            _collect_node_ids(child, collected)
    if_conditions = node.get("if_conditions")
    if isinstance(if_conditions, dict):
        _collect_node_ids(if_conditions, collected)


def _collect_trace_ids(trace: Dict[str, Any], collected: Set[str]) -> None:
    """Recursively collects all node IDs visited in an evaluation trace tree."""
    if not isinstance(trace, dict):
        return
    node_id = trace.get("id")
    if node_id:
        collected.add(node_id)
    children = trace.get("children")
    if isinstance(children, list):
        for child in children:
            _collect_trace_ids(child, collected)


# ============================================================================================
# 1. TEST 1: PYDANTIC SCHEMA VALIDATION & ROUND-TRIP SERIALIZATION INTEGRITY
# ============================================================================================
def test_ui_export_pydantic_schema_validation_roundtrip():
    """
    Validates that the raw visual editor JSON export matches StrategyV2ConfigData schema
    verbatim, and can be serialized back and forth with zero field drops.
    """
    raw_config = load_raw_ui_config()

    # 1. Validate against Pydantic StrategyV2ConfigData
    validated_v2 = schemas.StrategyV2ConfigData.model_validate(raw_config)
    assert validated_v2.strategy_name == "VisualBuilderStrategy"
    assert validated_v2.symbol == "BTCUSDT"
    assert validated_v2.marketType == "FUTURES"
    assert validated_v2.entryTrigger.type == "on_candle_close"
    assert validated_v2.entryTrigger.timeframe == "5m"

    # Verify counts match the UI structure
    assert len(validated_v2.filters.children or []) == 10
    assert len(validated_v2.entryConditions.children or []) == 18
    assert len(validated_v2.positionManagement or []) == 7

    # 2. Round-trip serialization
    dumped = validated_v2.model_dump(by_alias=True, exclude_none=True)
    assert dumped["symbol"] == raw_config["symbol"]
    assert dumped["marketType"] == raw_config["marketType"]
    assert (
        dumped["entryTrigger"]["timeframe"] == raw_config["entryTrigger"]["timeframe"]
    )

    # 3. Validate against StrategyConfigCreate (API Endpoint Schema)
    strategy_create_payload = {
        "name": "Live Master Strategy from UI",
        "description": "Exported from React Strategy Editor",
        "config_data": raw_config,
        "symbol_selection_mode": "STATIC",
        "symbols": ["BTCUSDT"],
        "use_ml_confirmation": False,
    }
    api_schema = schemas.StrategyConfigCreate.model_validate(strategy_create_payload)
    assert api_schema.name == "Live Master Strategy from UI"
    assert api_schema.config_data is not None


# ============================================================================================
# 2. TEST 2: VISUAL BUILDER INITIALIZATION & FULL AST EVALUATION ACROSS EXCHANGES
# ============================================================================================
@pytest.mark.parametrize("exchange", ["bybit", "binance", "okx", "weex"])
def test_ui_export_execution_and_trace_completeness(exchange: str):
    """
    Initializes VisualBuilderStrategy with the raw UI export and evaluates all filters
    and entry condition trees across multiple exchange contexts.
    Verifies that every single node ID in the UI export is evaluated without silent drops.
    """
    raw_config = load_raw_ui_config()
    pair_info, market_data = create_exchange_context(
        exchange=exchange, symbol="BTCUSDT"
    )

    strategy = VisualBuilderStrategy(params={"config": raw_config, "enabled": True})
    assert strategy.NAME == "VisualBuilderStrategy"

    # 1. Evaluate Filters
    filters_tree = raw_config.get("filters", {})
    res_filters, trace_filters = strategy._evaluate_condition_tree(
        node=filters_tree,
        pair_info=pair_info,
        market_data=market_data,
        prev_pair_info={},
        context={},
    )
    assert isinstance(res_filters, (bool, bool))
    assert isinstance(trace_filters, dict)

    # 2. Evaluate Entry Conditions
    entry_tree = raw_config.get("entryConditions", {})
    res_entry, trace_entry = strategy._evaluate_condition_tree(
        node=entry_tree,
        pair_info=pair_info,
        market_data=market_data,
        prev_pair_info={},
        context={},
    )
    assert isinstance(res_entry, (bool, bool))
    assert isinstance(trace_entry, dict)

    # 3. Verify that all node IDs from the UI JSON are present in the trace trees
    expected_filter_ids: Set[str] = set()
    _collect_node_ids(filters_tree, expected_filter_ids)
    evaluated_filter_ids: Set[str] = set()
    _collect_trace_ids(trace_filters, evaluated_filter_ids)

    assert expected_filter_ids.issubset(evaluated_filter_ids), (
        f"Missing filter nodes in evaluation trace: {expected_filter_ids - evaluated_filter_ids}"
    )

    expected_entry_ids: Set[str] = set()
    _collect_node_ids(entry_tree, expected_entry_ids)
    evaluated_entry_ids: Set[str] = set()
    _collect_trace_ids(trace_entry, evaluated_entry_ids)

    assert expected_entry_ids.issubset(evaluated_entry_ids), (
        f"Missing entry nodes in evaluation trace: {expected_entry_ids - evaluated_entry_ids}"
    )


# ============================================================================================
# 3. TEST 3: DYNAMIC LINK RESOLUTION IN VALUE_COMPARISON BLOCKS
# ============================================================================================
def test_ui_export_dynamic_block_result_links():
    """
    Verifies that the dynamic links in value_comparison referencing upstream block results
    (tape_analysis -> total_volume_usd, order_book_zone -> total_volume_usd)
    resolve accurately during strategy condition tree execution.
    """
    raw_config = load_raw_ui_config()
    pair_info, market_data = create_exchange_context(exchange="bybit", symbol="BTCUSDT")
    strategy = VisualBuilderStrategy(params={"config": raw_config, "enabled": True})

    # Find the tape_condition composite block in entryConditions
    tape_composite = None
    for child in raw_config["entryConditions"]["children"]:
        if child.get("compositeType") == "tape_condition":
            tape_composite = child
            break

    assert tape_composite is not None, (
        "tape_condition composite block not found in config"
    )

    # Evaluate the composite block with shared context
    shared_context: Dict[str, Any] = {}
    res, trace = strategy._evaluate_condition_tree(
        node=tape_composite,
        pair_info=pair_info,
        market_data=market_data,
        prev_pair_info={},
        context=shared_context,
    )

    assert isinstance(res, (bool, bool))
    assert len(trace.get("children", [])) == 2
    # Verify that the value_comparison node evaluated without throwing unresolved reference error
    val_comp_trace = trace["children"][1]
    assert "result" in val_comp_trace


# ============================================================================================
# 4. TEST 4: RESILIENCE TO EMPTY CONTAINERS & NULL PARAMETERS
# ============================================================================================
def test_ui_export_empty_containers_and_null_parameters_resilience():
    """
    Tests edge cases present in real visual editor exports:
    - Empty AND / OR containers
    - Empty senior_tf_confluence
    - null parameters (e.g. level_source: null, level_block_id: null)
    - Empty conditional_management
    Guarantees no unhandled NoneType / IndexError exceptions.
    """
    raw_config = load_raw_ui_config()
    pair_info, market_data = create_exchange_context(exchange="okx", symbol="BTCUSDT")
    strategy = VisualBuilderStrategy(params={"config": raw_config, "enabled": True})

    # 1. Direct evaluation of empty AND container
    empty_and = {"id": "test_empty_and", "type": "AND", "children": []}
    res_and, trace_and = strategy._evaluate_condition_tree(
        node=empty_and,
        pair_info=pair_info,
        market_data=market_data,
        prev_pair_info={},
        context={},
    )
    assert res_and is True, "Empty AND container must logically evaluate to True"

    # 2. Direct evaluation of empty OR container
    empty_or = {"id": "test_empty_or", "type": "OR", "children": []}
    res_or, trace_or = strategy._evaluate_condition_tree(
        node=empty_or,
        pair_info=pair_info,
        market_data=market_data,
        prev_pair_info={},
        context={},
    )
    assert res_or is False, "Empty OR container must logically evaluate to False"

    # 3. Direct evaluation of level_touch_analyzer with level_source: null
    touch_analyzer = {
        "id": "node_touch_null",
        "type": "level_touch_analyzer",
        "params": {
            "level_source": None,
            "lookback_candles": 50,
            "touch_tolerance_pct": 0.1,
            "min_touches": 2,
        },
    }
    res_touch, trace_touch = strategy._evaluate_condition_tree(
        node=touch_analyzer,
        pair_info=pair_info,
        market_data=market_data,
        prev_pair_info={},
        context={},
    )
    assert isinstance(res_touch, (bool, bool))
    assert isinstance(trace_touch, dict)


# ============================================================================================
# 5. TEST 5: FULL POSITION MANAGEMENT LIFECYCLE (ALL 7 PM BLOCKS IN THE EXPORT)
# ============================================================================================
@pytest.mark.asyncio
async def test_ui_export_full_position_management_execution():
    """
    Executes all 7 position management blocks from the UI export:
    - trailing_stop (Percentage 2%)
    - move_to_breakeven (RR multiplier 1, offset 2 pips)
    - conditional_exit
    - scale_in
    - dca_management (5 safety orders, 1.5x vol mult, 1% step)
    - grid_management (10 levels, 5% range)
    - conditional_management
    Validates that position state transitions execute seamlessly.
    """
    raw_config = load_raw_ui_config()
    pair_info, market_data = create_exchange_context(exchange="bybit", symbol="BTCUSDT")
    last_price = pair_info["last_price"]

    strategy = VisualBuilderStrategy(params={"config": raw_config, "enabled": True})

    # Create active open position
    pos = BasePosition(
        symbol="BTCUSDT",
        direction=SignalDirection.LONG,
        entry_price=last_price * 0.99,
        initial_quantity=1.0,
        remaining_quantity=1.0,
        entry_time=time.time() - 600,
        strategy="VisualBuilderStrategy",
        initial_stop_loss=last_price * 0.96,
        current_sl_price=last_price * 0.96,
        initial_take_profit=last_price * 1.05,
    )

    # 1. Trailing Stop
    trailing_block = next(
        b for b in raw_config["positionManagement"] if b["type"] == "trailing_stop"
    )
    updated_trail = strategy._handle_trailing_stop(trailing_block, pos, pair_info)
    assert updated_trail.current_sl_price is not None
    assert updated_trail.current_sl_price > 0

    # 2. Move to Break-even
    be_block = next(
        b for b in raw_config["positionManagement"] if b["type"] == "move_to_breakeven"
    )
    updated_be = strategy._handle_move_to_breakeven(be_block, pos, pair_info)
    assert updated_be is not None

    # 3. Full Async Position Management Pipeline
    exec_pos, exit_details = await strategy._execute_position_management(
        strategy_config=raw_config,
        position=pos,
        pair_info=pair_info,
        market_data=market_data,
        prev_pair_info=None,
    )
    assert exec_pos is not None
    assert exec_pos.symbol == "BTCUSDT"


# ============================================================================================
# 6. TEST 6: DYNAMIC PARAMETER LINKS IN SL/TP AND TRAILING STOP
# ============================================================================================
def test_ui_export_dynamic_param_links_in_sl_tp_and_trailing():
    """
    Verifies dynamic parameter linking in initialization (dynamic SL/TP linked to ATR indicator)
    and position management (trailing stop linked to indicator series).
    """
    raw_config = load_raw_ui_config()
    dynamic_config = json.loads(json.dumps(raw_config))

    # Add dynamic indicator references to initialization
    dynamic_config["initialization"]["params"]["sl_value"] = {
        "source": "indicator",
        "key": "atr",
    }
    dynamic_config["initialization"]["params"]["tp_value"] = {
        "source": "indicator",
        "key": "atr",
    }

    # Add dynamic indicator reference to trailing stop
    for block in dynamic_config["positionManagement"]:
        if block["type"] == "trailing_stop":
            block["params"]["value"] = {"source": "indicator", "key": "atr"}

    pair_info, market_data = create_exchange_context(exchange="bybit", symbol="BTCUSDT")
    strategy = VisualBuilderStrategy(params={"config": dynamic_config, "enabled": True})

    # Test dynamic value resolution in context
    context = {"pair_info": pair_info, "market_data": market_data}
    sl_resolved = strategy._resolve_value(
        dynamic_config["initialization"]["params"]["sl_value"], context
    )
    assert isinstance(sl_resolved, (int, float))
    assert sl_resolved > 0

    # Test trailing stop calculation with dynamic parameter
    pos = BasePosition(
        symbol="BTCUSDT",
        direction=SignalDirection.LONG,
        entry_price=pair_info["last_price"] * 0.99,
        initial_quantity=1.0,
        remaining_quantity=1.0,
        entry_time=time.time() - 300,
        strategy="VisualBuilderStrategy",
    )
    trail_block = dynamic_config["positionManagement"][0]
    updated_pos = strategy._handle_trailing_stop(trail_block, pos, pair_info)
    assert updated_pos.current_sl_price is not None


# ============================================================================================
# 7. TEST 7: FULL SIGNAL DISPATCH & DECISION TRACE GENERATION
# ============================================================================================
def test_ui_export_check_signal_sync_pipeline():
    """
    Verifies that the full check_signal_sync lifecycle executes smoothly on the UI export,
    generating valid signal outputs, calculated weights, and complete decision traces.
    """
    raw_config = load_raw_ui_config()
    pair_info, market_data = create_exchange_context(exchange="weex", symbol="BTCUSDT")
    strategy = VisualBuilderStrategy(params={"config": raw_config, "enabled": True})

    signal, weight, trace = strategy.check_signal_sync(
        pair_info=pair_info,
        market_data=market_data,
        prev_pair_info={},
    )

    assert isinstance(signal, (StrategySignal, type(None)))
    assert isinstance(weight, (int, float))
    if trace is not None:
        assert isinstance(trace, dict)
        assert "filters" in trace or "entryConditions" in trace or "type" in trace
