"""Add affiliate payouts table

Revision ID: 114355827cb0
Revises: f5d8ac71f614
Create Date: 2026-06-11 14:43:56.852408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "114355827cb0"
down_revision: Union[str, Sequence[str], None] = "f5d8ac71f614"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hub_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("secret_hash", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column(
            "version", sa.String(length=50), server_default="1.0.0", nullable=True
        ),
        sa.Column("last_ping", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hub_nodes_id"), "hub_nodes", ["id"], unique=False)
    op.create_index(
        op.f("ix_hub_nodes_node_uuid"), "hub_nodes", ["node_uuid"], unique=True
    )
    op.create_table(
        "affiliate_payouts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("payout_address", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_affiliate_payouts_user_id"),
        "affiliate_payouts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "hub_news_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("author_name", sa.String(length=50), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["news_id"], ["hub_news.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hub_news_comments_id"), "hub_news_comments", ["id"], unique=False
    )
    op.add_column(
        "hub_news",
        sa.Column("likes_count", sa.Integer(), server_default="0", nullable=True),
    )
    op.add_column(
        "hub_news",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "hub_topics",
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("hub_topics", sa.Column("tags", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hub_topics", "tags")
    op.drop_column("hub_topics", "is_verified")
    op.drop_column("hub_news", "is_pinned")
    op.drop_column("hub_news", "likes_count")
    op.drop_index(op.f("ix_hub_news_comments_id"), table_name="hub_news_comments")
    op.drop_table("hub_news_comments")
    op.drop_index(op.f("ix_affiliate_payouts_user_id"), table_name="affiliate_payouts")
    op.drop_table("affiliate_payouts")
    op.drop_index(op.f("ix_hub_nodes_node_uuid"), table_name="hub_nodes")
    op.drop_index(op.f("ix_hub_nodes_id"), table_name="hub_nodes")
    op.drop_table("hub_nodes")
    # ### end Alembic commands ###
