"""add_mining_and_rewards

Revision ID: 11dd202c080d
Revises: 2a487db2c451
Create Date: 2026-07-22 10:08:44.296109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11dd202c080d"
down_revision: Union[str, Sequence[str], None] = "2a487db2c451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mining_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_mining_enabled", sa.Boolean(), nullable=False),
        sa.Column("eligible_exchanges", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("daily_emission_base", sa.Float(), nullable=False),
        sa.Column("halving_interval_days", sa.Integer(), nullable=False),
        sa.Column("launch_date", sa.Date(), nullable=True),
        sa.Column("min_trade_duration_sec", sa.Integer(), nullable=False),
        sa.Column("min_trade_pnl_abs", sa.Float(), nullable=False),
        sa.Column("referral_mining_boost", sa.Float(), nullable=False),
        sa.Column("rebate_rates", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mining_epochs",
        sa.Column("epoch_date", sa.Date(), nullable=False),
        sa.Column("daily_emission", sa.Float(), nullable=False),
        sa.Column("total_rebate_pool", sa.Float(), nullable=False),
        sa.Column("total_distributed", sa.Float(), nullable=False),
        sa.Column("participating_nodes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("epoch_date"),
    )
    op.create_table(
        "node_mining_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "is_global_mining_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column(
            "user_reward_share_percent",
            sa.Float(),
            server_default="0.0",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hub_telemetry_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=False),
        sa.Column("pnl_percent", sa.Float(), nullable=True),
        sa.Column("trade_duration_sec", sa.Integer(), nullable=True),
        sa.Column("exit_reason", sa.String(length=50), nullable=True),
        sa.Column("trade_mode", sa.String(length=20), nullable=False),
        sa.Column("strategy_blocks", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("market_context", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("node_uuid", sa.String(length=36), nullable=True),
        sa.Column("exchange_id", sa.String(length=30), nullable=True),
        sa.Column("market_type", sa.String(length=20), nullable=True),
        sa.Column("broker_trade_id", sa.String(length=100), nullable=True),
        sa.Column("trade_volume_usdt", sa.Float(), nullable=True),
        sa.Column("estimated_rebate_usdt", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_mining_eligible", sa.Boolean(), nullable=False),
        sa.Column("reward_tokens", sa.Float(), nullable=False),
        sa.Column("epoch_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_uuid"],
            ["hub_nodes.node_uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_trade_id"),
    )
    op.create_index(
        op.f("ix_hub_telemetry_reports_created_at"),
        "hub_telemetry_reports",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hub_telemetry_reports_epoch_date"),
        "hub_telemetry_reports",
        ["epoch_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hub_telemetry_reports_exchange_id"),
        "hub_telemetry_reports",
        ["exchange_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hub_telemetry_reports_node_uuid"),
        "hub_telemetry_reports",
        ["node_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hub_telemetry_reports_symbol"),
        "hub_telemetry_reports",
        ["symbol"],
        unique=False,
    )
    op.create_table(
        "local_user_mining_stats",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "total_trade_volume_usdt", sa.Float(), server_default="0.0", nullable=False
        ),
        sa.Column(
            "estimated_rebate_usdt", sa.Float(), server_default="0.0", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "mining_ledger",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("node_uuid", sa.String(length=36), nullable=False),
        sa.Column("epoch_date", sa.Date(), nullable=False),
        sa.Column("base_reward", sa.Float(), nullable=False),
        sa.Column("referral_bonus", sa.Float(), nullable=False),
        sa.Column("welcome_bonus", sa.Float(), nullable=False),
        sa.Column("boost_multiplier", sa.Float(), nullable=False),
        sa.Column("total_reward", sa.Float(), nullable=False),
        sa.Column("total_rebate_usdt", sa.Float(), nullable=False),
        sa.Column("verified_trades_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["node_uuid"],
            ["hub_nodes.node_uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_uuid", "epoch_date", name="uix_ledger_node_epoch"),
    )
    op.create_index(
        op.f("ix_mining_ledger_epoch_date"),
        "mining_ledger",
        ["epoch_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mining_ledger_node_uuid"), "mining_ledger", ["node_uuid"], unique=False
    )
    op.add_column(
        "app_configs",
        sa.Column(
            "is_mining_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "hub_nodes",
        sa.Column("referrer_node_uuid", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "hub_nodes",
        sa.Column("node_referral_code", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "hub_nodes",
        sa.Column("total_mined", sa.Float(), server_default="0.0", nullable=False),
    )
    op.add_column(
        "hub_nodes",
        sa.Column(
            "has_welcome_bonus", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_hub_nodes_node_referral_code"),
        "hub_nodes",
        ["node_referral_code"],
        unique=True,
    )
    op.create_foreign_key(
        None, "hub_nodes", "hub_nodes", ["referrer_node_uuid"], ["node_uuid"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hub_nodes", type_="foreignkey")
    op.drop_index(op.f("ix_hub_nodes_node_referral_code"), table_name="hub_nodes")
    op.drop_column("hub_nodes", "has_welcome_bonus")
    op.drop_column("hub_nodes", "total_mined")
    op.drop_column("hub_nodes", "node_referral_code")
    op.drop_column("hub_nodes", "referrer_node_uuid")
    op.drop_column("app_configs", "is_mining_enabled")
    op.drop_index(op.f("ix_mining_ledger_node_uuid"), table_name="mining_ledger")
    op.drop_index(op.f("ix_mining_ledger_epoch_date"), table_name="mining_ledger")
    op.drop_table("mining_ledger")
    op.drop_table("local_user_mining_stats")
    op.drop_index(
        op.f("ix_hub_telemetry_reports_symbol"), table_name="hub_telemetry_reports"
    )
    op.drop_index(
        op.f("ix_hub_telemetry_reports_node_uuid"), table_name="hub_telemetry_reports"
    )
    op.drop_index(
        op.f("ix_hub_telemetry_reports_exchange_id"), table_name="hub_telemetry_reports"
    )
    op.drop_index(
        op.f("ix_hub_telemetry_reports_epoch_date"), table_name="hub_telemetry_reports"
    )
    op.drop_index(
        op.f("ix_hub_telemetry_reports_created_at"), table_name="hub_telemetry_reports"
    )
    op.drop_table("hub_telemetry_reports")
    op.drop_table("node_mining_config")
    op.drop_table("mining_epochs")
    op.drop_table("mining_config")
    # ### end Alembic commands ###
